spring.application.name=demo

feishu.app-id=cli_a9801e028af61013
feishu.app-secret=0gmXYM5RkwXbwhO8ZG2FucQhWQ0QDKh1

spring.datasource.url=jdbc:mysql://localhost:3306/bitable?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qwe123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver